#!/bin/bash

BATTERY_INFO=$(acpi -b | grep "Battery ${BLOCK_INSTANCE}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

URGENT_VALUE=5

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo "${BATTERY_POWER}% "
else
  echo "${BATTERY_POWER}%"
  echo "${BATTERY_POWER}%"
fi

if [[ "${BATTERY_STATE}" = "Discharging" ]]; then

  if [[ "${BATTERY_POWER}" -lt "20" ]]; then 
 		echo "#FF0000\n";
	elif [[ "${BATTERY_POWER}" -lt "40" ]]; then
		echo "#FFAE00\n";
	elif [[ "${BATTERY_POWER}" -lt "60" ]]; then
		echo "#FFF600\n";
	elif [[ "${BATTERY_POWER}" -lt "85" ]]; then
		echo "#A8FF00\n";
	elif [[ "${BATTERY_POWER}" -ge "85" ]]; then
		echo "#00FF00\n";
	fi

  if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
    exit 33
  fi

fi
