#!/bin/bash

BATTERY_INFO=$(acpi -b | grep "Battery ${BLOCK_INSTANCE}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

URGENT_VALUE=5

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo "${BATTERY_POWER}% "
  echo "${BATTERY_POWER}% "
	echo "$(getcolor i3.block.fgrnd)"
else
  echo "${BATTERY_POWER}%"
  echo "${BATTERY_POWER}%"
fi

if [[ "${BATTERY_STATE}" = "Discharging" ]]; then

  if [[ "${BATTERY_POWER}" -lt "20" ]]; then 
 		echo "$(getcolor i3.block.batt.5)";
	elif [[ "${BATTERY_POWER}" -lt "40" ]]; then
		echo "$(getcolor i3.block.batt.4)";
	elif [[ "${BATTERY_POWER}" -lt "60" ]]; then
		echo "$(getcolor i3.block.batt.3)";
	elif [[ "${BATTERY_POWER}" -lt "85" ]]; then
		echo "$(getcolor i3.block.batt.2)";
	elif [[ "${BATTERY_POWER}" -ge "85" ]]; then
		echo "$(getcolor i3.block.batt.1)";
	fi

  if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
    exit 33
  fi

fi
