#!/bin/bash

TYPE="${BLOCK_INSTANCE:-CAPS}"

lockLine=$(xset -q | grep "Num Lock")

capsLock=$(echo "${lockLine}" | awk -F ' ' '{print $4}')
numLock=$(echo "${lockLine}" | awk -F ' ' '{print $8}')
scrollLock=$(echo "${lockLine}" | awk -F ' ' '{print $12}')

if [[ "${TYPE}" == "CAPS" ]]; then
  checkLock="${capsLock}"
elif [[ "${TYPE}" == "NUM" ]]; then
  checkLock="${numLock}"
elif [[ "${TYPE}" == "SCROLL" ]]; then
  checkLock="${scrollLock}"
else
  exit
fi

if [[ "${checkLock}" == "on" ]]; then
  echo "${TYPE}"
fi
