#!/usr/bin/bash

URGENT_VALUE=25
#PACKAGE_COUNT=$(pacman -Qu | wc -l)
PACKAGE_COUNT=$(/usr/bin/checkupdates | wc -l)

# update on left click
case $BLOCK_BUTTON in
  1) termite -e 'sh -c "sudo pacman -Syu ; echo Done - Press enter to exit; read" ' && echo "" 
esac

if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
  echo "${PACKAGE_COUNT}" # full-text
  echo "${PACKAGE_COUNT}" # short-text
  echo ""
  if [[ "${PACKAGE_COUNT}" -gt "${URGENT_VALUE}" ]]; then
    exit 33
  fi
fi
