#!/bin/bash

ICON=/usr/share/icons/Paper/32x32/actions/system-reboot.png

. $HOME/.bash_profile
xrdb $HOME/.Xresources
killall dunst
i3-msg restart

notify-send 'Restart i3' 'Desktop env restarted' -i $ICON
