#!/bin/bash

case $BLOCK_BUTTON in
  3) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;  # right click, mute/unmute
  5) pactl set-sink-volume @DEFAULT_SINK@ +5% ;; # scroll up, increase
  4) pactl set-sink-volume @DEFAULT_SINK@ -5% ;; # scroll down, decrease
esac

statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')
label=♪

if [[ "${status}" == "on" ]]; then
  echo "${label} ${volume}%"
  echo "${label} ${volume}%"
  echo "$(getcolor i3.block.fgrnd)"
  if [[ ${volume} -gt 100 ]]; then
    exit 33
  fi
else
  echo "MUTE"
  echo "MUTE"
  echo "$(getcolor i3.block.inact)"
fi
