#!/bin/bash

. $DOTS/i3/scripts/set-label

case $BLOCK_BUTTON in
  1) $DOTS/i3/scripts/memory-processes
esac

used_mem=$(free | awk '/^Mem:/ {print int($3 / $2 * 100 + 0.5)}');
label=" ${used_mem}%"
set-label "$label" i3.block.fgrnd

if [[ ${used_mem} -gt 90 ]]; then
  exit 33
fi
