#!/usr/bin/bash

. $DOTS/i3/scripts/set-label

urgent_value=5
package_count=$(/usr/bin/checkupdates | wc -l)
label=" ${package_count}"

# update on left click
case $BLOCK_BUTTON in
  1) $DOTS/i3/scripts/run-updates 
esac

if [[ "${package_count}" -gt 0 ]]; then
  set-label "$label" i3.block.fgrnd
  if [[ "${package_count}" -gt "${urgent_value}" ]]; then
    exit 33
  fi
else
  echo "" # no updates
fi
