#!/bin/bash
# Based on http://openweathermap.org/current

. $DOTS/i3/scripts/set-label

# Get API key from cfg file
. $HOME/.config/i3/i3blocks/blocks/weather.cfg
api_key="${OPENWEATHER_API_KEY}"

# Check on http://openweathermap.org/find
city_id="${BLOCK_INSTANCE}"

urgent_low=0
urgent_high=30

icon_sun=""
icon_cloud=""
icon_rain=""
icon_storm=""
icon_snow=""
icon_fog=""
icon_night=""

celsius="℃"

weather_url="http://api.openweathermap.org/data/2.5/weather?id=${city_id}&appid=${api_key}&units=metric"

weather_info=$(wget -qO- "${weather_url}")
weather_main=$(echo "${weather_info}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
weather_code=$(echo "${weather_info}" | grep -o -e '\"id\":[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
weather_temp=$(echo "${weather_info}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
weather_icon=$(echo "${weather_info}" | grep -o -e '\"icon\":\"[a-zA-Z0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

case ${weather_code} in
  6*)     icon=${icon_snow} ;; # snow
  3*|5*)  icon=${icon_rain} ;; # rain, drizzle
  800*) # clear
    case ${weather_icon} in
      01n)  icon=${icon_night} ;; # night
      *)    icon=${icon_sun} ;; # day
    esac ;; 
  80*)    icon=${icon_cloud} ;; # cloudy
  7*)     icon=${icon_fog} ;; # fog
  2*)     icon=${icon_storm} ;; # storm
  9*)     icon=${weather_main} ;; # extreme
  *)      icon="?" # probably no internet
esac

set-label "${icon} ${weather_temp}${celsius}" i3.block.fgrnd

if [[ "${weather_temp}" -lt "${urgent_low}" ]] || [[ "${weather_temp}" -gt "${urgent_high}" ]]; then
  exit 33
fi
