#!/bin/bash
# Based on http://openweathermap.org/current

# Get API key from cfg file
. $HOME/.config/i3/i3blocks/blocks/weather.cfg
API_KEY="${OPENWEATHER_API_KEY}"

# Check on http://openweathermap.org/find
CITY_ID="${BLOCK_INSTANCE}"

URGENT_LOWER=0
URGENT_HIGHER=30

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""
ICON_NIGHT=""

SYMBOL_CELSIUS="℃"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_CODE=$(echo "${WEATHER_INFO}" | grep -o -e '\"id\":[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_ICON=$(echo "${WEATHER_INFO}" | grep -o -e '\"icon\":\"[a-zA-Z0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

case ${WEATHER_CODE} in
  6*)     ICON=${ICON_SNOW} ;; # snow
  3*|5*)  ICON=${ICON_RAINY} ;; # rain, drizzle
  800*) # clear
    case ${WEATHER_ICON} in
      01n)  ICON=${ICON_NIGHT} ;; # night
      *)    ICON=${ICON_SUNNY} ;; # day
    esac ;; 
  80*)    ICON=${ICON_CLOUDY} ;; # cloudy
  7*)     ICON=${ICON_FOG} ;; # fog
  2*)     ICON=${ICON_STORM} ;; # storm
  9*)     ICON=${WEATHER_MAIN} ;; # extreme
  *)      ICON="?" # probably no internet
esac

echo "${ICON} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
echo "${ICON} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
echo "$(getcolor i3.block.fgrnd)"

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
